// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myessay.model;

import com.myessay.model.JobDataOnDemand;
import com.myessay.model.JobIntegrationTest;
import com.myessay.model.JobRepository;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect JobIntegrationTest_Roo_IntegrationTest {
    
    declare @type: JobIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: JobIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: JobIntegrationTest: @Transactional;
    
    @Autowired
    JobDataOnDemand JobIntegrationTest.dod;
    
    @Autowired
    JobRepository JobIntegrationTest.jobRepository;
    
    @Test
    public void JobIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Job' failed to initialize correctly", dod.getRandomJob());
        long count = jobRepository.count();
        Assert.assertTrue("Counter for 'Job' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void JobIntegrationTest.testFind() {
        Job obj = dod.getRandomJob();
        Assert.assertNotNull("Data on demand for 'Job' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Job' failed to provide an identifier", id);
        obj = jobRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Job' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Job' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void JobIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Job' failed to initialize correctly", dod.getRandomJob());
        long count = jobRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Job', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Job> result = jobRepository.findAll();
        Assert.assertNotNull("Find all method for 'Job' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Job' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void JobIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Job' failed to initialize correctly", dod.getRandomJob());
        long count = jobRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Job> result = jobRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Job' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Job' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void JobIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Job' failed to initialize correctly", dod.getRandomJob());
        Job obj = dod.getNewTransientJob(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Job' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Job' identifier to be null", obj.getId());
        try {
            jobRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        jobRepository.flush();
        Assert.assertNotNull("Expected 'Job' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void JobIntegrationTest.testDelete() {
        Job obj = dod.getRandomJob();
        Assert.assertNotNull("Data on demand for 'Job' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Job' failed to provide an identifier", id);
        obj = jobRepository.findOne(id);
        jobRepository.delete(obj);
        jobRepository.flush();
        Assert.assertNull("Failed to remove 'Job' with identifier '" + id + "'", jobRepository.findOne(id));
    }
    
}
