// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myessay.model;

import com.myessay.model.Order;
import com.myessay.model.OrderDataOnDemand;
import com.myessay.model.OrderRepository;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect OrderDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OrderDataOnDemand: @Component;
    
    private Random OrderDataOnDemand.rnd = new SecureRandom();
    
    private List<Order> OrderDataOnDemand.data;
    
    @Autowired
    OrderRepository OrderDataOnDemand.orderRepository;
    
    public Order OrderDataOnDemand.getNewTransientOrder(int index) {
        Order obj = new Order();
        setCoupon(obj, index);
        setCourseLevel(obj, index);
        setCreateDate(obj, index);
        setCustomerId(obj, index);
        setDeadLine(obj, index);
        setFileId(obj, index);
        setFormat(obj, index);
        setIncludeFigure(obj, index);
        setNote(obj, index);
        setOrderStatus(obj, index);
        setReferencing(obj, index);
        setSourcesCount(obj, index);
        setStartDate(obj, index);
        setSubjectId(obj, index);
        setTaskId(obj, index);
        setWordCount(obj, index);
        return obj;
    }
    
    public void OrderDataOnDemand.setCoupon(Order obj, int index) {
        String coupon = "coupon_" + index;
        if (coupon.length() > 35) {
            coupon = coupon.substring(0, 35);
        }
        obj.setCoupon(coupon);
    }
    
    public void OrderDataOnDemand.setCourseLevel(Order obj, int index) {
        String courseLevel = "courseLevel_" + index;
        if (courseLevel.length() > 35) {
            courseLevel = courseLevel.substring(0, 35);
        }
        obj.setCourseLevel(courseLevel);
    }
    
    public void OrderDataOnDemand.setCreateDate(Order obj, int index) {
        Calendar createDate = Calendar.getInstance();
        obj.setCreateDate(createDate);
    }
    
    public void OrderDataOnDemand.setCustomerId(Order obj, int index) {
        Integer customerId = new Integer(index);
        obj.setCustomerId(customerId);
    }
    
    public void OrderDataOnDemand.setDeadLine(Order obj, int index) {
        Calendar deadLine = Calendar.getInstance();
        obj.setDeadLine(deadLine);
    }
    
    public void OrderDataOnDemand.setFileId(Order obj, int index) {
        Integer fileId = new Integer(index);
        obj.setFileId(fileId);
    }
    
    public void OrderDataOnDemand.setFormat(Order obj, int index) {
        String format = "format_" + index;
        if (format.length() > 30) {
            format = format.substring(0, 30);
        }
        obj.setFormat(format);
    }
    
    public void OrderDataOnDemand.setIncludeFigure(Order obj, int index) {
        String includeFigure = "includeFigure_" + index;
        if (includeFigure.length() > 30) {
            includeFigure = includeFigure.substring(0, 30);
        }
        obj.setIncludeFigure(includeFigure);
    }
    
    public void OrderDataOnDemand.setNote(Order obj, int index) {
        String note = "note_" + index;
        if (note.length() > 255) {
            note = note.substring(0, 255);
        }
        obj.setNote(note);
    }
    
    public void OrderDataOnDemand.setOrderStatus(Order obj, int index) {
        String orderStatus = "orderStatus_" + index;
        if (orderStatus.length() > 45) {
            orderStatus = orderStatus.substring(0, 45);
        }
        obj.setOrderStatus(orderStatus);
    }
    
    public void OrderDataOnDemand.setReferencing(Order obj, int index) {
        String referencing = "referencing_" + index;
        if (referencing.length() > 30) {
            referencing = referencing.substring(0, 30);
        }
        obj.setReferencing(referencing);
    }
    
    public void OrderDataOnDemand.setSourcesCount(Order obj, int index) {
        Short sourcesCount = new Integer(index).shortValue();
        obj.setSourcesCount(sourcesCount);
    }
    
    public void OrderDataOnDemand.setStartDate(Order obj, int index) {
        Calendar startDate = Calendar.getInstance();
        obj.setStartDate(startDate);
    }
    
    public void OrderDataOnDemand.setSubjectId(Order obj, int index) {
        Integer subjectId = new Integer(index);
        obj.setSubjectId(subjectId);
    }
    
    public void OrderDataOnDemand.setTaskId(Order obj, int index) {
        Integer taskId = new Integer(index);
        obj.setTaskId(taskId);
    }
    
    public void OrderDataOnDemand.setWordCount(Order obj, int index) {
        Integer wordCount = new Integer(index);
        obj.setWordCount(wordCount);
    }
    
    public Order OrderDataOnDemand.getSpecificOrder(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Order obj = data.get(index);
        Integer id = obj.getId();
        return orderRepository.findOne(id);
    }
    
    public Order OrderDataOnDemand.getRandomOrder() {
        init();
        Order obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return orderRepository.findOne(id);
    }
    
    public boolean OrderDataOnDemand.modifyOrder(Order obj) {
        return false;
    }
    
    public void OrderDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = orderRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Order' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Order>();
        for (int i = 0; i < 10; i++) {
            Order obj = getNewTransientOrder(i);
            try {
                orderRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            orderRepository.flush();
            data.add(obj);
        }
    }
    
}
