// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myessay.model;

import com.myessay.model.SubjectDataOnDemand;
import com.myessay.model.SubjectIntegrationTest;
import com.myessay.model.SubjectRepository;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SubjectIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SubjectIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SubjectIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SubjectIntegrationTest: @Transactional;
    
    @Autowired
    SubjectDataOnDemand SubjectIntegrationTest.dod;
    
    @Autowired
    SubjectRepository SubjectIntegrationTest.subjectRepository;
    
    @Test
    public void SubjectIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Subject' failed to initialize correctly", dod.getRandomSubject());
        long count = subjectRepository.count();
        Assert.assertTrue("Counter for 'Subject' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SubjectIntegrationTest.testFind() {
        Subject obj = dod.getRandomSubject();
        Assert.assertNotNull("Data on demand for 'Subject' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Subject' failed to provide an identifier", id);
        obj = subjectRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Subject' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Subject' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SubjectIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Subject' failed to initialize correctly", dod.getRandomSubject());
        long count = subjectRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Subject', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Subject> result = subjectRepository.findAll();
        Assert.assertNotNull("Find all method for 'Subject' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Subject' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SubjectIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Subject' failed to initialize correctly", dod.getRandomSubject());
        long count = subjectRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Subject> result = subjectRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Subject' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Subject' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SubjectIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Subject' failed to initialize correctly", dod.getRandomSubject());
        Subject obj = dod.getNewTransientSubject(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Subject' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Subject' identifier to be null", obj.getId());
        try {
            subjectRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        subjectRepository.flush();
        Assert.assertNotNull("Expected 'Subject' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SubjectIntegrationTest.testDelete() {
        Subject obj = dod.getRandomSubject();
        Assert.assertNotNull("Data on demand for 'Subject' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Subject' failed to provide an identifier", id);
        obj = subjectRepository.findOne(id);
        subjectRepository.delete(obj);
        subjectRepository.flush();
        Assert.assertNull("Failed to remove 'Subject' with identifier '" + id + "'", subjectRepository.findOne(id));
    }
    
}
