// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myessay.model;

import com.myessay.model.UploadfileDataOnDemand;
import com.myessay.model.UploadfileIntegrationTest;
import com.myessay.model.UploadfileRepository;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UploadfileIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UploadfileIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UploadfileIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UploadfileIntegrationTest: @Transactional;
    
    @Autowired
    UploadfileDataOnDemand UploadfileIntegrationTest.dod;
    
    @Autowired
    UploadfileRepository UploadfileIntegrationTest.uploadfileRepository;
    
    @Test
    public void UploadfileIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Uploadfile' failed to initialize correctly", dod.getRandomUploadfile());
        long count = uploadfileRepository.count();
        Assert.assertTrue("Counter for 'Uploadfile' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UploadfileIntegrationTest.testFind() {
        Uploadfile obj = dod.getRandomUploadfile();
        Assert.assertNotNull("Data on demand for 'Uploadfile' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Uploadfile' failed to provide an identifier", id);
        obj = uploadfileRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Uploadfile' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Uploadfile' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UploadfileIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Uploadfile' failed to initialize correctly", dod.getRandomUploadfile());
        long count = uploadfileRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Uploadfile', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Uploadfile> result = uploadfileRepository.findAll();
        Assert.assertNotNull("Find all method for 'Uploadfile' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Uploadfile' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UploadfileIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Uploadfile' failed to initialize correctly", dod.getRandomUploadfile());
        long count = uploadfileRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Uploadfile> result = uploadfileRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Uploadfile' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Uploadfile' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UploadfileIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Uploadfile' failed to initialize correctly", dod.getRandomUploadfile());
        Uploadfile obj = dod.getNewTransientUploadfile(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Uploadfile' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Uploadfile' identifier to be null", obj.getId());
        try {
            uploadfileRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        uploadfileRepository.flush();
        Assert.assertNotNull("Expected 'Uploadfile' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UploadfileIntegrationTest.testDelete() {
        Uploadfile obj = dod.getRandomUploadfile();
        Assert.assertNotNull("Data on demand for 'Uploadfile' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Uploadfile' failed to provide an identifier", id);
        obj = uploadfileRepository.findOne(id);
        uploadfileRepository.delete(obj);
        uploadfileRepository.flush();
        Assert.assertNull("Failed to remove 'Uploadfile' with identifier '" + id + "'", uploadfileRepository.findOne(id));
    }
    
}
