// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myessay.model;

import com.myessay.model.UserinfoIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserinfoIntegrationTest_Roo_Configurable {
    
    declare @type: UserinfoIntegrationTest: @Configurable;
    
}
